sources:
  Customer:
    database: classicmodels
    host: localhost
    kind: mysql
    password: ${DB_PASSWORD_MYSQL}
    port: 3306
    user: root
  chinook:
    database: chinook
    host: localhost
    kind: postgres
    password: ${DB_PASSWORD_POSTGRES}
    port: 5432
    user: root
  superheroes:
    kind: "sqlite"
    database: "/Users/awaiskamran/downloads/superheroes.db"
tools:
  Customer_describe_table:
    description: Describe columns in a table of Customer
    kind: mysql-sql
    parameters:
    - description: Name of table to inspect
      name: table
      type: string
    source: Customer
    statement: SELECT column_name, data_type FROM information_schema.columns WHERE
      table_name = ?;
  Customer_execute_query:
    description: Execute arbitrary SQL on Customer within the 'sql' parameter
    kind: mysql-execute-sql
    source: Customer
  Customer_list_tables:
    description: List tables in Customer
    kind: mysql-sql
    source: Customer
    statement: SHOW TABLES;
  chinook_describe_table:
    description: Describe columns in a table of chinook
    kind: postgres-sql
    parameters:
    - description: Name of table to inspect
      name: table
      type: string
    source: chinook
    statement: SELECT column_name, data_type FROM information_schema.columns WHERE
      table_name = $1;
  chinook_execute_query:
    description: Execute arbitrary SQL on chinook within the 'sql' parameter
    kind: postgres-execute-sql
    source: chinook
  chinook_list_tables:
    description: List tables in chinook
    kind: postgres-sql
    source: chinook
    statement: SELECT table_name FROM information_schema.tables WHERE table_schema='public';
  superheroes-list-table:
    kind: "sqlite-sql"
    source: superheroes
    description: List all rows from a specific table
    templateParameters:
      - name: tableName
        type: string
        description: Table to select from
    statement: SELECT * FROM {{.tableName}}; 
toolsets:
  Customer_toolset:
  - Customer_list_tables
  - Customer_describe_table
  - Customer_execute_query
  chinook_toolset:
  - chinook_list_tables
  - chinook_describe_table
  - chinook_execute_query
  superheroes_toolset:
  - superheroes-list-table
