sources:
  Customer:
    database: classicmodels
    host: localhost
    kind: mysql
    password: ${DB_PASSWORD_MYSQL}
    port: 3306
    user: ${DB_USER_MYSQL}
tools:
  Customer_describe_table:
    description: Describe columns in a table of Customer
    kind: mysql-sql
    parameters:
    - description: Name of table to inspect
      name: table
      type: string
    source: Customer
    statement: SELECT column_name, data_type FROM information_schema.columns WHERE table_name = ?;
  Customer_execute_query:
    description: Execute arbitrary SQL on Customer within the 'sql' parameter
    kind: mysql-execute-sql
    source: Customer
  Customer_list_tables:
    description: List tables in Customer
    kind: mysql-sql
    source: Customer
    statement: show tables;
toolsets:
  Customer_toolset:
  - Customer_list_tables
  - Customer_describe_table
  - Customer_execute_query
